apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: logging-app-monitor
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: logging-app
  podMetricsEndpoints:
  - port: "8888"
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default