namespaceOverride: ""
rbac:
  create: true
releaseLabel: true
prometheus:
  prometheusSpec:
    scrapeInterval: "60s"
    remoteWrite:
    - url:  http://lgtm-mimir-nginx:80/api/v1/push
    externalLabels:
       environment: mimir
  monitor:
    enabled: true
    interval: ""
    sampleLimit: 0
    targetLimit: 0
    labelLimit: 0
    labelNameLengthLimit: 0
    labelValueLengthLimit: 0
    scrapeTimeout: ""
    proxyUrl: ""
    honorLabels: true
    metricRelabelings: []
    relabelings: []

# For cloud provider environments turn to false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false

grafana:
  enabled: false
  forceDeployDashboards: true

alertmanager:
  enabled: false

# Node Exporter configuration for Docker Desktop
prometheus-node-exporter:
  hostNetwork: false
  hostPID: false
  hostRootFsMount:
    enabled: false
  extraArgs:
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|cgroup|cgroup2|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tmpfs|tracefs)$
    - --no-collector.powersupplyclass
    - --no-collector.rapl